
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

cloud:

homeassistant:
  country: US
  latitude: !secret home_latitude
  longitude: !secret home_longitude

zone: 
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 200

camera:
  - platform: ffmpeg
    input: rtsp://127.0.0.1:8554/front-door-camera
  
logger:
  default: info
  logs:
    homeassistant.components.person: debug

sensor:
  platform: weatheralerts
  state: NJ
  zone: 27
  county: 5

influxdb:
  database: Homeassistant
  username: !secret influx_username
  password: !secret influx_password
  max_retries: 3
  default_measurement: state


binary_sensor:
  - platform: ping
    host: 192.168.100.1
    name: router
  - platform: ping
    host: www.google.com
    name: google

notify:
  - platform: discord
    name: weatherbot
    token: !secret weather_token
  - platform: discord
    name: homebot
    token: !secret home_token
# Text to speech
tts:
  - platform: google_translate
  
light:
  - platform: group
    name: Living Room Lights
    entities:
      - light.fireplace_lamp
      - light.living_room_window
  - platform: group
    name: Bedroom
    entities:
      - light.bedroom_corner_light
      - light.chris_nightstand
      - light.heather_nightstand

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
